include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AppSyncUnified-FrontBoard

AppSyncUnified-FrontBoard_FILES = AppSyncUnified-FrontBoard.x
AppSyncUnified-FrontBoard_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
